name: MacOS

on:
  pull_request:
    branches: [ stable, develop ]

  push:
    branches: [ stable, develop ]

  workflow_dispatch:

jobs:
  PDC:
    runs-on: macos-13
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: .github/workflows/dependencies-macos.sh

      - name: Build PDC
        run: |
          mkdir build && cd build
          cmake ../ -DBUILD_MPI_TESTING=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DPDC_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc

          make -j 2

      - name: Test PDC
        working-directory: build
        run: |
          sudo sh -c 'echo "`ipconfig getifaddr en0` PDC" >> /etc/hosts'
          sudo scutil --set HostName PDC

          export HG_TRANSPORT="sockets"
          export PDC_CONFIGURATION=$(realpath ../.github/workflows)

          echo "PDC_CONFIGURATION = $PDC_CONFIGURATION"

          ctest -L serial

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: build
          retention-days: 1
