name: NERSC

on:
  pull_request_target

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  sync-with-nersc:
    needs: authorize
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Setup git
        run: |
          git config --global user.name "PDC BOT"
          git config --global user.email "pdc@example.com"
    
      - name: Create PR branch
        run: |
          git fetch origin pull/${PR_NUMBER}/head:PR-${PR_NUMBER}
          git remote add gitlab https://${NERSC_GITLAB_TOKEN_NAME}:${NERSC_GITLAB_TOKEN}@${NERSC_GITLAB_URL}
          echo "https://${NERSC_GITLAB_TOKEN_NAME}:----@${NERSC_GITLAB_URL}"
          git checkout PR-${PR_NUMBER}
          git push gitlab -u PR-${PR_NUMBER}
